// src/data/staffData.js
export const staffData = [
  {
    id: 1,
    name: "James Carter",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    status: "Online",
    roles: ["Owner / Manager"],
    position: "Senior Manager",
    phone: "(+1) 123 456 7890",
    services: ["Management", "Client Relations", "Strategic Planning"],
    hasUpcomingBookings: true,
    workingShifts: [
      { day: "Sunday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Monday", isOn: true, startTime: "09:00", endTime: "17:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Tuesday", isOn: true, startTime: "09:00", endTime: "17:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Wednesday", isOn: true, startTime: "09:00", endTime: "17:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Thursday", isOn: true, startTime: "09:00", endTime: "17:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Friday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Saturday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
    ],
  },
  {
    id: 2,
    name: "Olivia Johnson",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    status: "Offline",
    roles: ["Owner / Manager"],
    position: "Junior Manager",
    phone: "(+1) 234 567 8901",
    services: ["HR", "Staff Training", "Scheduling"],
    hasUpcomingBookings: false,
    workingShifts: [
      { day: "Sunday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Monday", isOn: true, startTime: "10:00", endTime: "18:00", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Tuesday", isOn: true, startTime: "10:00", endTime: "18:00", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Wednesday", isOn: true, startTime: "10:00", endTime: "18:00", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Thursday", isOn: true, startTime: "10:00", endTime: "18:00", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Friday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Saturday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
    ],
  },
  {
    id: 3,
    name: "Sophia Miller",
    image: "https://randomuser.me/api/portraits/women/68.jpg",
    status: "Online",
    roles: ["Employee", "Receptionist"],
    position: "Employee & Cashier",
    phone: "(+1) 345 678 9012",
    services: ["Appointments", "Billing", "Customer Service", "Product Sales"],
    hasUpcomingBookings: true,
    workingShifts: [
      { day: "Sunday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Monday", isOn: true, startTime: "08:00", endTime: "14:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Tuesday", isOn: true, startTime: "08:00", endTime: "14:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Wednesday", isOn: true, startTime: "10:00", endTime: "16:00", breakOn: true, breakStartTime: "13:00", breakEndTime: "14:00" },
      { day: "Thursday", isOn: true, startTime: "12:00", endTime: "18:00", breakOn: true, breakStartTime: "15:00", breakEndTime: "16:00" },
      { day: "Friday", isOn: true, startTime: "09:00", endTime: "15:00", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Saturday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
    ],
  },
  {
    id: 4,
    name: "William Baker",
    image: "https://randomuser.me/api/portraits/men/47.jpg",
    status: "Break",
    roles: ["Employee", "Receptionist"],
    position: "Employee & Cashier",
    phone: "(+1) 456 789 0123",
    services: ["Check-ins", "Phone Support", "Cash Handling", "Data Entry"],
    hasUpcomingBookings: false,
    workingShifts: [
      { day: "Sunday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Monday", isOn: true, startTime: "14:00", endTime: "20:00", breakOn: true, breakStartTime: "17:00", breakEndTime: "18:00" },
      { day: "Tuesday", isOn: true, startTime: "14:00", endTime: "20:00", breakOn: true, breakStartTime: "17:00", breakEndTime: "18:00" },
      { day: "Wednesday", isOn: true, startTime: "12:00", endTime: "18:00", breakOn: true, breakStartTime: "15:00", breakEndTime: "16:00" },
      { day: "Thursday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Friday", isOn: true, startTime: "10:00", endTime: "16:00", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Saturday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
    ],
  },
  {
    id: 5,
    name: "Ava Thompson",
    image: "https://randomuser.me/api/portraits/women/50.jpg",
    status: "Online",
    roles: ["Employee", "Receptionist"],
    position: "Employee & Cashier", // Changed from "Employee & Cashier" to fit new roles more naturally if she's a therapist
    phone: "(+1) 234 567 890",
    services: [
      "Swedish",
      "Deep Tissue",
      "Hot Stone",
      "Aromatherapy",
      "Thai",
      "Reflexology",
      "Prenatal",
      "Trigger Point",
    ],
    hasUpcomingBookings: true,
    workingShifts: [
      { day: "Sunday", isOn: true, startTime: "08:00", endTime: "14:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Monday", isOn: true, startTime: "08:00", endTime: "14:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Tuesday", isOn: true, startTime: "10:00", endTime: "16:00", breakOn: true, breakStartTime: "13:00", breakEndTime: "14:00" },
      { day: "Wednesday", isOn: true, startTime: "12:00", endTime: "18:00", breakOn: true, breakStartTime: "15:00", breakEndTime: "16:00" },
      { day: "Thursday", isOn: true, startTime: "09:00", endTime: "15:00", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Friday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Saturday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
    ],
  },
  {
    id: 6,
    name: "Isabella Martinez",
    image: "https://randomuser.me/api/portraits/women/75.jpg",
    status: "Online",
    roles: ["Employee", "Massage Therapist"], // Added "Massage Therapist" role
    position: "Junior Massage Therapist",
    phone: "(+1) 567 890 1234",
    services: ["Swedish", "Deep Tissue", "Hot Stone", "Foot Massage"],
    hasUpcomingBookings: false,
    workingShifts: [
      { day: "Sunday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Monday", isOn: true, startTime: "09:00", endTime: "17:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Tuesday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Wednesday", isOn: true, startTime: "09:00", endTime: "17:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Thursday", isOn: true, startTime: "10:00", endTime: "18:00", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Friday", isOn: true, startTime: "09:00", endTime: "17:00", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Saturday", isOn: true, startTime: "09:00", endTime: "15:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
    ],
  },
  {
    id: 7,
    name: "Daniel Lewis",
    image: "https://randomuser.me/api/portraits/men/29.jpg",
    status: "Online",
    roles: ["Receptionist"],
    position: "Senior Receptionist",
    phone: "(+1) 678 901 2345",
    services: ["Advanced Booking", "Complaint Resolution", "Event Coordination"],
    hasUpcomingBookings: false,
    workingShifts: [
      { day: "Sunday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Monday", isOn: true, startTime: "10:00", endTime: "18:00", breakOn: true, breakStartTime: "14:00", breakEndTime: "15:00" },
      { day: "Tuesday", isOn: true, startTime: "10:00", endTime: "18:00", breakOn: true, breakStartTime: "14:00", breakEndTime: "15:00" },
      { day: "Wednesday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Thursday", isOn: true, startTime: "10:00", endTime: "18:00", breakOn: true, breakStartTime: "14:00", breakEndTime: "15:00" },
      { day: "Friday", isOn: true, startTime: "10:00", endTime: "18:00", breakOn: true, breakStartTime: "14:00", breakEndTime: "15:00" },
      { day: "Saturday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
    ],
  },
  {
    id: 8,
    name: "Ella Scott",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
    status: "Offline",
    roles: ["Employee", "Hair Stylist"], // Added "Hair Stylist" role
    position: "Senior Hair Stylist",
    phone: "(+1) 789 012 3456",
    services: ["Haircuts", "Coloring", "Styling", "Treatments", "Extensions"],
    hasUpcomingBookings: true,
    workingShifts: [
      { day: "Sunday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Monday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Tuesday", isOn: true, startTime: "09:00", endTime: "17:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Wednesday", isOn: true, startTime: "09:00", endTime: "17:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Thursday", isOn: true, startTime: "09:00", endTime: "17:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Friday", isOn: true, startTime: "10:00", endTime: "18:00", breakOn: true, breakStartTime: "14:00", breakEndTime: "15:00" },
      { day: "Saturday", isOn: true, startTime: "09:00", endTime: "16:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
    ],
  },
  {
    id: 9,
    name: "Lucas Allen",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    status: "Break",
    roles: ["Employee", "Coach"], // Added "Coach" role
    position: "Wellness Coach",
    phone: "(+1) 890 123 4567",
    services: ["Consultation", "Diet Plans", "Fitness Training", "Mindfulness"],
    hasUpcomingBookings: false,
    workingShifts: [
      { day: "Sunday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Monday", isOn: true, startTime: "11:00", endTime: "19:00", breakOn: true, breakStartTime: "14:00", breakEndTime: "15:00" },
      { day: "Tuesday", isOn: true, startTime: "11:00", endTime: "19:00", breakOn: true, breakStartTime: "14:00", breakEndTime: "15:00" },
      { day: "Wednesday", isOn: true, startTime: "13:00", endTime: "20:00", breakOn: true, breakStartTime: "16:00", breakEndTime: "17:00" },
      { day: "Thursday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Friday", isOn: true, startTime: "11:00", endTime: "19:00", breakOn: true, breakStartTime: "14:00", breakEndTime: "15:00" },
      { day: "Saturday", isOn: true, startTime: "10:00", endTime: "14:00", breakOn: false, breakStartTime: "", breakEndTime: "" },
    ],
  },
  {
    id: 10,
    name: "Chloe Davis",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    status: "Online",
    roles: ["Employee", "Esthetician"],
    position: "Senior Esthetician",
    phone: "(+1) 987 654 3210",
    services: ["Facials", "Chemical Peels", "Microdermabrasion", "Waxing", "Eyelash Extensions"],
    hasUpcomingBookings: true,
    workingShifts: [
      { day: "Sunday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Monday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Tuesday", isOn: true, startTime: "10:00", endTime: "18:00", breakOn: true, breakStartTime: "13:00", breakEndTime: "14:00" },
      { day: "Wednesday", isOn: true, startTime: "10:00", endTime: "18:00", breakOn: true, breakStartTime: "13:00", breakEndTime: "14:00" },
      { day: "Thursday", isOn: true, startTime: "10:00", endTime: "18:00", breakOn: true, breakStartTime: "13:00", breakEndTime: "14:00" },
      { day: "Friday", isOn: true, startTime: "09:00", endTime: "17:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Saturday", isOn: true, startTime: "09:00", endTime: "16:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
    ],
  },
  {
    id: 11,
    name: "Noah Martinez",
    image: "https://randomuser.me/api/portraits/men/10.jpg",
    status: "Offline",
    roles: ["Employee", "Physical Therapist"],
    position: "Lead Physical Therapist",
    phone: "(+1) 111 222 3333",
    services: ["Rehabilitation", "Injury Assessment", "Pain Management", "Exercise Therapy"],
    hasUpcomingBookings: false,
    workingShifts: [
      { day: "Sunday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Monday", isOn: true, startTime: "08:00", endTime: "16:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Tuesday", isOn: true, startTime: "08:00", endTime: "16:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Wednesday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
      { day: "Thursday", isOn: true, startTime: "09:00", endTime: "17:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Friday", isOn: true, startTime: "09:00", endTime: "17:00", breakOn: true, breakStartTime: "12:00", breakEndTime: "13:00" },
      { day: "Saturday", isOn: false, startTime: "", endTime: "", breakOn: false, breakStartTime: "", breakEndTime: "" },
    ],
  },
];