// src/data/staffData.js
export const staffData = [
  {
    id: 1,
    name: "James Carter",
    image: "https://randomuser.me/api/portraits/men/32.jpg", // Replace with actual image paths
    status: "Online",
    roles: ["Owner / Manager"],
    position: "Senior Manager",
  },
  {
    id: 2,
    name: "Olivia Johnson",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    status: "Offline",
    roles: ["Owner / Manager"],
    position: "Junior Manager",
  },
  {
    id: 3,
    name: "Sophia Miller",
    image: "https://randomuser.me/api/portraits/women/68.jpg",
    status: "Online",
    roles: ["Employee", "Receptionist"],
    position: "Employee & Cashier",
  },
  {
    id: 4,
    name: "William Baker",
    image: "https://randomuser.me/api/portraits/men/47.jpg",
    status: "Break",
    roles: ["Employee", "Receptionist"],
    position: "Employee & Cashier",
  },
  {
    id: 5,
    name: "Ava Thompson",
    image: "https://randomuser.me/api/portraits/women/50.jpg",
    status: "Online",
    roles: ["Employee", "Receptionist"],
    position: "Employee & Cashier",
  },
  {
    id: 6,
    name: "Isabella Martinez",
    image: "https://randomuser.me/api/portraits/women/75.jpg",
    status: "Online",
    roles: ["Employee"],
    position: "Junior Massage Therapist",
  },
  {
    id: 7,
    name: "Daniel Lewis",
    image: "https://randomuser.me/api/portraits/men/29.jpg",
    status: "Online",
    roles: ["Receptionist"],
    position: "Senior Receptionist",
  },
  {
    id: 8,
    name: "Ella Scott",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
    status: "Offline",
    roles: ["Employee"],
    position: "Senior Hair Stylist",
  },
  {
    id: 9,
    name: "Lucas Allen",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    status: "Break",
    roles: ["Employee"],
    position: "Wellness Coach",
  },
];