// // Mock service for pending bookings data
export const getPendingBookings = () => {
  return [
    {
      id: "1",
      scheduledDate: "09/01/2025",
      scheduledTime: "13:00",
      clientName: "Emily",
      clientPhone: "(+1) 234 567 890",
      services: [
        "Classic Ombre",
        "Smooth/Scalp treatment",
        "Cut + Treatment",
        "Moisture treatment",
      ],
      staffName: "Pixe Nomad",
      totalDuration: "1h 45m",
      totalPrice: "264.60",
      status: "Pending",
      avatar: "E",
    },
    {
      id: "2",
      scheduledDate: "12/01/2025",
      scheduledTime: "14:00",
      clientName: "Alexander",
      clientPhone: "(+1) 234 567 890",
      services: [
        "Haircut",
        "Smooth/Scalp treatment",
        "Cut + Treatment",
        "Moisture treatment",
      ],
      staffName: "Code Voyager",
      totalDuration: "2h 30m",
      totalPrice: "264.60",
      status: "Pending",
      avatar: "A",
    },
    {
      id: "3",
      scheduledDate: "14/01/2025",
      scheduledTime: "14:00",
      clientName: "Scarlett",
      clientPhone: "(+1) 234 567 890",
      services: [
        "Haircut",
        "Smooth/Scalp treatment",
        "Cut + Treatment",
        "Moisture treatment",
      ],
      staffName: "Pixe Nomad",
      totalDuration: "30m",
      totalPrice: "264.60",
      status: "Pending",
      avatar: "S",
    },
    {
      id: "4",
      scheduledDate: "18/01/2025",
      scheduledTime: "14:00",
      clientName: "Joseph",
      clientPhone: "(+1) 234 567 890",
      services: [
        "Haircut",
        "Smooth/Scalp treatment",
        "Cut + Treatment",
        "Moisture treatment",
      ],
      staffName: "John Doe",
      totalDuration: "1h",
      totalPrice: "264.60",
      status: "Pending",
      avatar: "J",
    },
    {
      id: "5", // Original "Thomas" entry
      scheduledDate: "20/01/2025",
      scheduledTime: "14:00",
      clientName: "Thomas",
      clientPhone: "(+1) 234 567 890",
      services: [
        "Haircut",
        "Smooth/Scalp treatment",
        "Cut + Treatment",
        "Moisture treatment",
      ],
      staffName: "Echo Sage",
      totalDuration: "1h 45m",
      totalPrice: "264.60",
      status: "Pending",
      avatar: "T",
    },
    {
      id: "6", // Unique ID
      scheduledDate: "21/01/2025",
      scheduledTime: "10:00",
      clientName: "Olivia",
      clientPhone: "(+1) 234 567 891",
      services: ["Manicure", "Pedicure"],
      staffName: "Grace Kelly",
      totalDuration: "1h 30m",
      totalPrice: "120.00",
      status: "Pending",
      avatar: "O",
    },
    {
      id: "7", // Unique ID
      scheduledDate: "22/01/2025",
      scheduledTime: "11:00",
      clientName: "James",
      clientPhone: "(+1) 234 567 892",
      services: ["Beard Trim", "Haircut"],
      staffName: "John Doe",
      totalDuration: "45m",
      totalPrice: "50.00",
      status: "Pending",
      avatar: "J",
    },
    {
      id: "8", // Unique ID
      scheduledDate: "23/01/2025",
      scheduledTime: "15:00",
      clientName: "Sophia",
      clientPhone: "(+1) 234 567 893",
      services: ["Facial", "Eyelash Extensions"],
      staffName: "Pixe Nomad",
      totalDuration: "2h",
      totalPrice: "180.00",
      status: "Pending",
      avatar: "S",
    },
    {
      id: "9", // Unique ID
      scheduledDate: "24/01/2025",
      scheduledTime: "16:00",
      clientName: "William",
      clientPhone: "(+1) 234 567 894",
      services: ["Hair Coloring", "Hair Wash"],
      staffName: "Code Voyager",
      totalDuration: "2h 15m",
      totalPrice: "300.00",
      status: "Pending",
      avatar: "W",
    },
    {
      id: "10", // Unique ID
      scheduledDate: "25/01/2025",
      scheduledTime: "09:30",
      clientName: "Isabella",
      clientPhone: "(+1) 234 567 895",
      services: ["Massage", "Body Scrub"],
      staffName: "Echo Sage",
      totalDuration: "1h 30m",
      totalPrice: "250.00",
      status: "Pending",
      avatar: "I",
    },
    {
      id: "11", // Unique ID
      scheduledDate: "26/01/2025",
      scheduledTime: "13:45",
      clientName: "Daniel",
      clientPhone: "(+1) 234 567 896",
      services: ["Shave", "Hot Towel Treatment"],
      staffName: "John Doe",
      totalDuration: "40m",
      totalPrice: "60.00",
      status: "Pending",
      avatar: "D",
    },
    {
      id: "12", // Unique ID
      scheduledDate: "27/01/2025",
      scheduledTime: "17:00",
      clientName: "Mia",
      clientPhone: "(+1) 234 567 897",
      services: ["Nail Art", "Gel Polish"],
      staffName: "Grace Kelly",
      totalDuration: "1h",
      totalPrice: "90.00",
      status: "Pending",
      avatar: "M",
    },
    {
      id: "13", // Unique ID
      scheduledDate: "28/01/2025",
      scheduledTime: "08:30",
      clientName: "Liam",
      clientPhone: "(+1) 234 567 898",
      services: ["Hair Perm", "Conditioning Treatment"],
      staffName: "Pixe Nomad",
      totalDuration: "2h 45m",
      totalPrice: "280.00",
      status: "Pending",
      avatar: "L",
    },
    {
      id: "14", // Unique ID
      scheduledDate: "29/01/2025",
      scheduledTime: "10:15",
      clientName: "Charlotte",
      clientPhone: "(+1) 234 567 899",
      services: ["Bridal Makeup", "Hair Styling"],
      staffName: "Code Voyager",
      totalDuration: "3h",
      totalPrice: "500.00",
      status: "Pending",
      avatar: "C",
    },
  ];
};