export const getPendingBookings = () => {
  return [
    {
      id: "1",
      scheduledDate: "09/01/2025",
      scheduledTime: "13:00",
      clientName: "Emily",
      clientPhone: "(+1) 234 567 890",
      serviceDetails: [
        {
          id: "1",
          name: "Classic Ombre",
          duration: "2h45m",
          price: "770.00",
          tags: ["Smooth / Scalp treatment"],
        },
        {
          id: "2",
          name: "Reverse Ombre",
          duration: "3h30m",
          price: "100.00",
          tags: ["Shadow Root"],
        },
      ],
      staffName: "Pixe Nomad",
      totalDuration: "1h 45m",
      subtotal: "1220.00",
      tax: "0.00",
      discount: "20%",
      discountAmount: "244.00",
      totalPrice: "976.00",
      status: "Completed",
      avatar: "E",
      notes: "Shop recommends booking a trim every 6-8 weeks",
    },
    {
      id: "2",
      scheduledDate: "12/01/2025",
      scheduledTime: "14:00",
      clientName: "Alexander",
      clientPhone: "(+1) 234 567 890",
      serviceDetails: [
        {
          id: "1",
          name: "Classic Ombre",
          duration: "2h45m",
          price: "770.00",
          tags: ["Smooth / Scalp treatment"],
        },
        {
          id: "2",
          name: "Reverse Ombre",
          duration: "3h30m",
          price: "100.00",
          tags: ["Shadow Root"],
        },
        {
          id: "4", // Assuming Balayage with Toner corresponds to service ID 4
          name: "Balayage with Toner",
          duration: "30m",
          price: "100.00",
          tags: [],
        },
      ],
      staffName: "Code Voyager",
      totalDuration: "2h 30m",
      subtotal: "550.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "550.00",
      status: "Pending",
      avatar: "A",
      notes: "Client prefers minimal styling products",
    },
    {
      id: "3",
      scheduledDate: "14/01/2028",
      scheduledTime: "14:00",
      clientName: "Scarlett",
      clientPhone: "(+1) 234 567 890",
      serviceDetails: [
        {
          id: "temp-1", // Assign temporary IDs or align with your services array if these exist
          name: "Haircut",
          duration: "45m",
          price: "100.00",
          tags: ["Shadow Root"],
        },
        {
          id: "temp-3",
          name: "Cut + Treatment",
          duration: "1h 30m",
          price: "150.00",
          tags: ["Smooth/Scalp treatment"],
        },
        {
          id: "temp-4",
          name: "Moisture treatment",
          duration: "1h",
          price: "100.00",
          tags: [],
        },
      ],
      staffName: "Pixe Nomad",
      totalDuration: "30m", // This duration might need adjustment based on the sum of service durations
      subtotal: "550.00",
      tax: "0.00",
      discount: "10%",
      discountAmount: "55.00",
      totalPrice: "495.00",
      status: "Cancelled",
      avatar: "S",
      notes: "",
    },
    {
      id: "4",
      scheduledDate: "18/01/2025",
      scheduledTime: "14:00",
      clientName: "Joseph",
      clientPhone: "(+1) 234 567 890",
      serviceDetails: [
        {
          id: "temp-5",
          name: "Haircut",
          duration: "45m",
          price: "100.00",
          tags: ["Smooth/Scalp treatment"],
        },
        {
          id: "temp-7",
          name: "Cut + Treatment",
          duration: "1h 30m",
          price: "150.00",
          tags: ["Moisture treatment"],
        },
      ],
      staffName: "John Doe",
      totalDuration: "1h", // This duration might need adjustment based on the sum of service durations
      subtotal: "550.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "550.00",
      status: "Confirmed",
      avatar: "J",
      notes: "Client has a sensitive scalp",
    },
    {
      id: "5",
      scheduledDate: "20/01/20250",
      scheduledTime: "14:00",
      clientName: "Thomas",
      clientPhone: "(+1) 234 567 890",
      serviceDetails: [
        {
          id: "temp-9",
          name: "Haircut",
          duration: "45m",
          price: "100.00",
          tags: ["Smooth/Scalp treatment"],
        },
        {
          id: "temp-10",
          name: "Cut + Treatment",
          duration: "1h 30m",
          price: "150.00",
          tags: ["Moisture treatment"],
        },
      ],
      staffName: "Echo Sage",
      totalDuration: "1h 45m", // This duration might need adjustment based on the sum of service durations
      subtotal: "550.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "550.00",
      status: "Cancelled",
      avatar: "T",
      notes: "",
    },
    {
      id: "6",
      scheduledDate: "21/01/2025",
      scheduledTime: "10:00",
      clientName: "Olivia",
      clientPhone: "(+1) 234 567 891",
      serviceDetails: [
        {
          id: "temp-13",
          name: "Manicure",
          duration: "1h",
          price: "60.00",
          tags: [],
        },
        {
          id: "temp-14",
          name: "Pedicure",
          duration: "1h",
          price: "60.00",
          tags: [],
        },
      ],
      staffName: "Grace Kelly",
      totalDuration: "1h 30m", // This duration might need adjustment based on the sum of service durations
      subtotal: "120.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "120.00",
      status: "Pending",
      avatar: "O",
      notes: "",
    },
    {
      id: "7",
      scheduledDate: "22/01/2025",
      scheduledTime: "11:00",
      clientName: "James",
      clientPhone: "(+1) 234 567 892",
      serviceDetails: [
        {
          id: "temp-15",
          name: "Beard Trim",
          duration: "30m",
          price: "20.00",
          tags: [],
        },
        {
          id: "temp-16",
          name: "Haircut",
          duration: "45m",
          price: "30.00",
          tags: [],
        },
      ],
      staffName: "John Doe",
      totalDuration: "45m", // This duration might need adjustment based on the sum of service durations
      subtotal: "50.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "50.00",
      status: "Completed",
      avatar: "J",
      notes: "",
    },
    {
      id: "8",
      scheduledDate: "23/01/2025",
      scheduledTime: "15:00",
      clientName: "Sophia",
      clientPhone: "(+1) 234 567 893",
      serviceDetails: [
        {
          id: "temp-17",
          name: "Facial",
          duration: "1h",
          price: "100.00",
          tags: [],
        },
        {
          id: "temp-18",
          name: "Eyelash Extensions",
          duration: "1h 30m",
          price: "80.00",
          tags: [],
        },
      ],
      staffName: "Pixe Nomad",
      totalDuration: "2h", // This duration might need adjustment based on the sum of service durations
      subtotal: "180.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "180.00",
      status: "No Show",
      avatar: "S",
      notes: "",
    },
    {
      id: "9",
      scheduledDate: "24/01/2025",
      scheduledTime: "16:00",
      clientName: "William",
      clientPhone: "(+1) 234 567 894",
      serviceDetails: [
        {
          id: "temp-19",
          name: "Hair Coloring",
          duration: "2h",
          price: "250.00",
          tags: [],
        },
        {
          id: "temp-20",
          name: "Hair Wash",
          duration: "30m",
          price: "50.00",
          tags: [],
        },
      ],
      staffName: "Code Voyager",
      totalDuration: "2h 15m", // This duration might need adjustment based on the sum of service durations
      subtotal: "300.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "300.00",
      status: "Pending",
      avatar: "W",
      notes: "",
    },
    {
      id: "10",
      scheduledDate: "25/01/2025",
      scheduledTime: "09:30",
      clientName: "Isabella",
      clientPhone: "(+1) 234 567 895",
      serviceDetails: [
        {
          id: "temp-21",
          name: "Massage",
          duration: "1h",
          price: "150.00",
          tags: [],
        },
        {
          id: "temp-22",
          name: "Body Scrub",
          duration: "1h",
          price: "100.00",
          tags: [],
        },
      ],
      staffName: "Echo Sage",
      totalDuration: "1h 30m", // This duration might need adjustment based on the sum of service durations
      subtotal: "250.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "250.00",
      status: "Pending",
      avatar: "I",
      notes: "",
    },
    {
      id: "11",
      scheduledDate: "26/01/2025",
      scheduledTime: "13:45",
      clientName: "Daniel",
      clientPhone: "(+1) 234 567 896",
      serviceDetails: [
        {
          id: "temp-23",
          name: "Shave",
          duration: "30m",
          price: "30.00",
          tags: [],
        },
        {
          id: "temp-24",
          name: "Hot Towel Treatment",
          duration: "30m",
          price: "30.00",
          tags: [],
        },
      ],
      staffName: "John Doe",
      totalDuration: "40m", // This duration might need adjustment based on the sum of service durations
      subtotal: "60.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "60.00",
      status: "Pending",
      avatar: "D",
      notes: "",
    },
    {
      id: "12",
      scheduledDate: "27/01/2025",
      scheduledTime: "17:00",
      clientName: "Mia",
      clientPhone: "(+1) 234 567 897",
      serviceDetails: [
        {
          id: "temp-25",
          name: "Nail Art",
          duration: "45m",
          price: "50.00",
          tags: [],
        },
        {
          id: "temp-26",
          name: "Gel Polish",
          duration: "30m",
          price: "40.00",
          tags: [],
        },
      ],
      staffName: "Grace Kelly",
      totalDuration: "1h", // This duration might need adjustment based on the sum of service durations
      subtotal: "90.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "90.00",
      status: "Pending",
      avatar: "M",
      notes: "",
    },
    {
      id: "13",
      scheduledDate: "28/01/2025",
      scheduledTime: "08:30",
      clientName: "Liam",
      clientPhone: "(+1) 234 567 898",
      serviceDetails: [
        {
          id: "temp-27",
          name: "Hair Perm",
          duration: "2h",
          price: "200.00",
          tags: [],
        },
        {
          id: "temp-28",
          name: "Conditioning Treatment",
          duration: "45m",
          price: "80.00",
          tags: [],
        },
      ],
      staffName: "Pixe Nomad",
      totalDuration: "2h 45m", // This duration might need adjustment based on the sum of service durations
      subtotal: "280.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "280.00",
      status: "Pending",
      avatar: "L",
      notes: "",
    },
    {
      id: "14",
      scheduledDate: "29/01/2025",
      scheduledTime: "10:15",
      clientName: "Charlotte",
      clientPhone: "(+1) 234 567 899",
      serviceDetails: [
        {
          id: "temp-29",
          name: "Bridal Makeup",
          duration: "2h 30m",
          price: "350.00",
          tags: [],
        },
        {
          id: "temp-30",
          name: "Hair Styling",
          duration: "1h",
          price: "150.00",
          tags: [],
        },
      ],
      staffName: "Code Voyager",
      totalDuration: "3h", // This duration might need adjustment based on the sum of service durations
      subtotal: "500.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "500.00",
      status: "Pending",
      avatar: "C",
      notes: "",
    },
  ];
};

export const getPendingBookingsById = (id) => {
  const bookings = getPendingBookings();
  return bookings.find((booking) => booking.id === id) || null;
};