export const getPendingBookings = () => {
  return [
    {
      id: "1",
      scheduledDate: "09/01/2025",
      scheduledTime: "13:00:",
      clientName: "Emily",
      clientPhone: "(+1) 234 567 890",
      serviceDetails: [
        { name: "Classic Ombre", price: "770.00" },
        { name: "Smooth/Scalp treatment", price: "200.00" },
        { name: "Cut + Treatment", price: "150.00" },
        { name: "Moisture treatment", price: "100.00" },
      ],
      staffName: "Pixe Nomad",
      totalDuration: "1h 45m",
      subtotal: "1220.00",
      tax: "0.00",
      discount: "20%", // 20% discount
      discountAmount: "244.00", // 20% of 1220.00
      totalPrice: "976.00", // 1220.00 - 244.00
      status: "Completed",
      avatar: "E",
      notes: "Shop recommends booking a trim every 6-8 weeks",
    },
    {
      id: "2",
      scheduledDate: "12/01/2025",
      scheduledTime: "14:00",
      clientName: "Alexander",
      clientPhone: "(+1) 234 567 890",
      serviceDetails: [
        { name: "Haircut", price: "100.00" },
        { name: "Smooth/Scalp treatment", price: "200.00" },
        { name: "Cut + Treatment", price: "150.00" },
        { name: "Moisture treatment", price: "100.00" },
      ],
      staffName: "Code Voyager",
      totalDuration: "2h 30m",
      subtotal: "550.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "550.00",
      status: "Pending",
      avatar: "A",
      notes: "Client prefers minimal styling products",
    },
    {
      id: "3",
      scheduledDate: "14/01/2025",
      scheduledTime: "14:00",
      clientName: "Scarlett",
      clientPhone: "(+1) 234 567 890",
      serviceDetails: [
        { name: "Haircut", price: "100.00" },
        { name: "Smooth/Scalp treatment", price: "200.00" },
        { name: "Cut + Treatment", price: "150.00" },
        { name: "Moisture treatment", price: "100.00" },
      ],
      staffName: "Pixe Nomad",
      totalDuration: "30m",
      subtotal: "550.00",
      tax: "0.00",
      discount: "10%",
      discountAmount: "55.00",
      totalPrice: "495.00",
      status: "Cancelled",
      avatar: "S",
      notes: "",
    },
    {
      id: "4",
      scheduledDate: "18/01/2025",
      scheduledTime: "14:00",
      clientName: "Joseph",
      clientPhone: "(+1) 234 567 890",
      serviceDetails: [
        { name: "Haircut", price: "100.00" },
        { name: "Smooth/Scalp treatment", price: "200.00" },
        { name: "Cut + Treatment", price: "150.00" },
        { name: "Moisture treatment", price: "100.00" },
      ],
      staffName: "John Doe",
      totalDuration: "1h",
      subtotal: "550.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "550.00",
      status: "Confirmed",
      avatar: "J",
      notes: "Client has a sensitive scalp",
    },
    {
      id: "5",
      scheduledDate: "20/01/2025",
      scheduledTime: "14:00",
      clientName: "Thomas",
      clientPhone: "(+1) 234 567 890",
      serviceDetails: [
        { name: "Haircut", price: "100.00" },
        { name: "Smooth/Scalp treatment", price: "200.00" },
        { name: "Cut + Treatment", price: "150.00" },
        { name: "Moisture treatment", price: "100.00" },
      ],
      staffName: "Echo Sage",
      totalDuration: "1h 45m",
      subtotal: "550.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "550.00",
      status: "Cancelled",
      avatar: "T",
      notes: "",
    },
    {
      id: "6",
      scheduledDate: "21/01/2025",
      scheduledTime: "10:00",
      clientName: "Olivia",
      clientPhone: "(+1) 234 567 891",
      serviceDetails: [
        { name: "Manicure", price: "60.00" },
        { name: "Pedicure", price: "60.00" },
      ],
      staffName: "Grace Kelly",
      totalDuration: "1h 30m",
      subtotal: "120.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "120.00",
      status: "Pending",
      avatar: "O",
      notes: "",
    },
    {
      id: "7",
      scheduledDate: "22/01/2025",
      scheduledTime: "11:00",
      clientName: "James",
      clientPhone: "(+1) 234 567 892",
      serviceDetails: [
        { name: "Beard Trim", price: "20.00" },
        { name: "Haircut", price: "30.00" },
      ],
      staffName: "John Doe",
      totalDuration: "45m",
      subtotal: "50.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "50.00",
      status: "Completed",
      avatar: "J",
      notes: "",
    },
    {
      id: "8",
      scheduledDate: "23/01/2025",
      scheduledTime: "15:00",
      clientName: "Sophia",
      clientPhone: "(+1) 234 567 893",
      serviceDetails: [
        { name: "Facial", price: "100.00" },
        { name: "Eyelash Extensions", price: "80.00" },
      ],
      staffName: "Pixe Nomad",
      totalDuration: "2h",
      subtotal: "180.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "180.00",
      status: "No Show",
      avatar: "S",
      notes: "",
    },
    {
      id: "9",
      scheduledDate: "24/01/2025",
      scheduledTime: "16:00",
      clientName: "William",
      clientPhone: "(+1) 234 567 894",
      serviceDetails: [
        { name: "Hair Coloring", price: "250.00" },
        { name: "Hair Wash", price: "50.00" },
      ],
      staffName: "Code Voyager",
      totalDuration: "2h 15m",
      subtotal: "300.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "300.00",
      status: "Pending",
      avatar: "W",
      notes: "",
    },
    {
      id: "10",
      scheduledDate: "25/01/2025",
      scheduledTime: "09:30",
      clientName: "Isabella",
      clientPhone: "(+1) 234 567 895",
      serviceDetails: [
        { name: "Massage", price: "150.00" },
        { name: "Body Scrub", price: "100.00" },
      ],
      staffName: "Echo Sage",
      totalDuration: "1h 30m",
      subtotal: "250.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "250.00",
      status: "Pending",
      avatar: "I",
      notes: "",
    },
    {
      id: "11",
      scheduledDate: "26/01/2025",
      scheduledTime: "13:45",
      clientName: "Daniel",
      clientPhone: "(+1) 234 567 896",
      serviceDetails: [
        { name: "Shave", price: "30.00" },
        { name: "Hot Towel Treatment", price: "30.00" },
      ],
      staffName: "John Doe",
      totalDuration: "40m",
      subtotal: "60.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "60.00",
      status: "Pending",
      avatar: "D",
      notes: "",
    },
    {
      id: "12",
      scheduledDate: "27/01/2025",
      scheduledTime: "17:00",
      clientName: "Mia",
      clientPhone: "(+1) 234 567 897",
      serviceDetails: [
        { name: "Nail Art", price: "50.00" },
        { name: "Gel Polish", price: "40.00" },
      ],
      staffName: "Grace Kelly",
      totalDuration: "1h",
      subtotal: "90.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "90.00",
      status: "Pending",
      avatar: "M",
      notes: "",
    },
    {
      id: "13",
      scheduledDate: "28/01/2025",
      scheduledTime: "08:30",
      clientName: "Liam",
      clientPhone: "(+1) 234 567 898",
      serviceDetails: [
        { name: "Hair Perm", price: "200.00" },
        { name: "Conditioning Treatment", price: "80.00" },
      ],
      staffName: "Pixe Nomad",
      totalDuration: "2h 45m",
      subtotal: "280.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "280.00",
      status: "Pending",
      avatar: "L",
      notes: "",
    },
    {
      id: "14",
      scheduledDate: "29/01/2025",
      scheduledTime: "10:15",
      clientName: "Charlotte",
      clientPhone: "(+1) 234 567 899",
      serviceDetails: [
        { name: "Bridal Makeup", price: "350.00" },
        { name: "Hair Styling", price: "150.00" },
      ],
      staffName: "Code Voyager",
      totalDuration: "3h",
      subtotal: "500.00",
      tax: "0.00",
      discount: "0%",
      discountAmount: "0.00",
      totalPrice: "500.00",
      status: "Pending",
      avatar: "C",
      notes: "",
    },
  ];
};


export const getPendingBookingsById = (id) => {
  const bookings = getPendingBookings();
  return bookings.find((booking) => booking.id === id) || null;
};