export const clientData = [
  {
    id: "CLT-1001",
    name: "Tran Huyen",
    avatar: "T",
    avatarColor: "avatar-teal",
    gender: "Female",
    dob: "01/01/1999",
    phone: "(+1) 234 567 890",
    isVerified: false,
    city: "Jerusalem, Israel",
    type: "Standard",
  },
  {
    id: "CLT-1002",
    name: "James Carter",
    avatar: "J",
    avatarColor: "avatar-blue",
    gender: "Male",
    dob: "01/01/1999",
    phone: "(+1) 234 567 890",
    isVerified: true,
    city: "Tel Aviv, Israel",
    type: "VIP",
  },
  {
    id: "CLT-1003",
    name: "Olivia Bennett",
    avatar: "O",
    avatarColor: "avatar-purple",
    gender: "Others",
    dob: "01/01/1999",
    phone: "(+1) 234 567 890",
    isVerified: false,
    city: "Haifa, Israel",
    type: "Standard",
  },
  {
    id: "CLT-1004",
    name: "Ethan Hayes",
    avatar: "E",
    avatarColor: "avatar-red",
    gender: "Male",
    dob: "01/01/1999",
    phone: "(+1) 234 567 890",
    isVerified: true,
    city: "Jerusalem, Israel",
    type: "VIP",
  },
  {
    id: "CLT-1005",
    name: "Sophia Mitchell",
    avatar: "S",
    avatarColor: "avatar-green",
    gender: "Female",
    dob: "01/01/1999",
    phone: "(+1) 234 567 890",
    isVerified: true,
    city: "Jerusalem, Israel",
    type: "VIP",
  },
  {
    id: "CLT-1006",
    name: "Daniel Reed",
    avatar: "D",
    avatarColor: "avatar-indigo",
    gender: "Male",
    dob: "01/01/1999",
    phone: "(+1) 234 567 890",
    isVerified: false,
    city: "Petah Tikva, Israel",
    type: "Standard",
  },
  {
    id: "CLT-1007",
    name: "Ava Sullivan",
    avatar: "A",
    avatarColor: "avatar-orange",
    gender: "Female",
    dob: "01/01/1999",
    phone: "(+1) 234 567 890",
    isVerified: true,
    city: "Jerusalem, Israel",
    type: "VIP",
  },
  {
    id: "CLT-1008",
    name: "Michael Brooks",
    avatar: "M",
    avatarColor: "avatar-violet",
    gender: "Others",
    dob: "01/01/1999",
    phone: "(+1) 234 567 890",
    isVerified: false,
    city: "Beersheba, Israel",
    type: "Standard",
  },
  // Adding more data
  {
    id: "CLT-1009",
    name: "Emma Johnson",
    avatar: "E",
    avatarColor: "avatar-pink",
    gender: "Female",
    dob: "15/04/1992",
    phone: "(+1) 345 678 901",
    isVerified: true,
    city: "Jerusalem, Israel",
    type: "VIP",
  },
  {
    id: "CLT-1010",
    name: "Noah Wilson",
    avatar: "N",
    avatarColor: "avatar-blue",
    gender: "Male",
    dob: "22/07/1988",
    phone: "(+1) 456 789 012",
    isVerified: false,
    city: "Tel Aviv, Israel",
    type: "Standard",
  },
  {
    id: "CLT-1011",
    name: "Isabella Garcia",
    avatar: "I",
    avatarColor: "avatar-teal",
    gender: "Female",
    dob: "03/12/1995",
    phone: "(+1) 567 890 123",
    isVerified: true,
    city: "Haifa, Israel",
    type: "Standard",
  },
  {
    id: "CLT-1012",
    name: "Liam Martinez",
    avatar: "L",
    avatarColor: "avatar-indigo",
    gender: "Male",
    dob: "18/09/1990",
    phone: "(+1) 678 901 234",
    isVerified: true,
    city: "Beersheba, Israel",
    type: "VIP",
  },
  {
    id: "CLT-1013",
    name: "Sophia Lopez",
    avatar: "S",
    avatarColor: "avatar-purple",
    gender: "Female",
    dob: "27/02/1993",
    phone: "(+1) 789 012 345",
    isVerified: false,
    city: "Jerusalem, Israel",
    type: "Standard",
  },
  {
    id: "CLT-1014",
    name: "Ethan Robinson",
    avatar: "E",
    avatarColor: "avatar-orange",
    gender: "Male",
    dob: "14/06/1987",
    phone: "(+1) 890 123 456",
    isVerified: true,
    city: "Tel Aviv, Israel",
    type: "VIP",
  },
  {
    id: "CLT-1015",
    name: "Mia Clark",
    avatar: "M",
    avatarColor: "avatar-green",
    gender: "Female",
    dob: "30/11/1991",
    phone: "(+1) 901 234 567",
    isVerified: true,
    city: "Haifa, Israel",
    type: "Standard",
  },
  {
    id: "CLT-1016",
    name: "Aiden Rodriguez",
    avatar: "A",
    avatarColor: "avatar-red",
    gender: "Male",
    dob: "09/08/1994",
    phone: "(+1) 012 345 678",
    isVerified: false,
    city: "Petah Tikva, Israel",
    type: "Standard",
  },
  {
    id: "CLT-1017",
    name: "Charlotte Lee",
    avatar: "C",
    avatarColor: "avatar-violet",
    gender: "Female",
    dob: "21/03/1989",
    phone: "(+1) 123 456 789",
    isVerified: true,
    city: "Jerusalem, Israel",
    type: "VIP",
  },
  {
    id: "CLT-1018",
    name: "Benjamin Walker",
    avatar: "B",
    avatarColor: "avatar-blue",
    gender: "Male",
    dob: "05/05/1986",
    phone: "(+1) 234 567 890",
    isVerified: false,
    city: "Beersheba, Israel",
    type: "Standard",
  },
  {
    id: "CLT-1019",
    name: "Amelia Hall",
    avatar: "A",
    avatarColor: "avatar-teal",
    gender: "Female",
    dob: "12/10/1997",
    phone: "(+1) 345 678 901",
    isVerified: true,
    city: "Tel Aviv, Israel",
    type: "VIP",
  },
  {
    id: "CLT-1020",
    name: "Lucas Allen",
    avatar: "L",
    avatarColor: "avatar-indigo",
    gender: "Male",
    dob: "29/01/1996",
    phone: "(+1) 456 789 012",
    isVerified: true,
    city: "Haifa, Israel",
    type: "Standard",
  },
];

export const getClients = () => {
  return clientData;
};

export const searchClients = (query) => {
  if (!query) return clientData;

  const lowercaseQuery = query.toLowerCase();
  return clientData.filter(
    (client) =>
      client.name.toLowerCase().includes(lowercaseQuery) ||
      client.phone.toLowerCase().includes(lowercaseQuery)
  );
};

export const filterClientsByCity = (city) => {
  if (!city || city === "All cities") return clientData;

  return clientData.filter((client) => client.city.includes(city));
};

export const filterClientsByGenders = (genders) => {
  if (!genders.length) return clientData;

  return clientData.filter((client) => genders.includes(client.gender));
};
